name: Generate Template

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up git
      run: |
        git config --global user.name 'china-place-bot'
        git config --global user.email 'china-place@users.noreply.github.com'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Images
      run: | 
        python main.py
        
    - name: Upload Images
      uses: actions/upload-artifact@v2
      with:
        name: template
        path: "./output.png"

    - name: Push Result
      run: |
        git add output.png
        git commit -am "[bot] generate template"
        git push
